#!/bin/bash

# color
N=`tput sgr0` # none
B=`tput bold` # bold
R=`tput setaf 1` # red
G=`tput setaf 2` # green
C=`tput setaf 4` # cyan

if [ $# -eq 0 ] 
then
    echo "Error(no args) : type 2 args; project name / language type"

    exit
elif [ $# -eq 1 ] 
then
    echo "Error(1 arg) : type 2 args; project name / language type"

    exit
elif [ $# -eq 2 ]
then
    if [ $2 == "c" ]
    then
        ycm_conf="$HOME/.vim/ycm_extra_conf_set/ycm_extra_conf.c.py"
        init_src="$HOME/.xnixc/resource/main.c"
        make_file="$HOME/.xnixc/resource/Makefile.c.conf"
    elif [ $2 == "cpp" ]
    then
        ycm_conf="$HOME/.vim/ycm_extra_conf_set/ycm_extra_conf.cpp.py"
        init_src="$HOME/.xnixc/resource/main.cpp"
        make_file="$HOME/.xnixc/resource/Makefile.cpp.conf"
    else
        echo "Error(invalid arg) : invalid language type; valid - c / cpp"

        exit
    fi

    tar="$PWD/$1"

    if [ -d $tar ] 
    then
        echo "Error : directory already exist; duplicate name"

        exit
    fi

    mkdir "$tar"
    echo ""
    echo "    ${B}${G}create${N} new ${R}${B}$2${N} project ${C}${B}$1${N}"

    sub_dirs=( "bin" "build" "doc" "include" "lib" "resource" "spike" "src" 
               "test" )
    
    for dir in "${sub_dirs[@]}"
    do
        mkdir "$tar/$dir"
        touch "$tar/$dir/.keep"
        echo -e "        ${G}${B}create${N} $dir/"
        if [ $dir == "src" ]
        then
            cp -- "$init_src" "$tar/$dir/"

            if [ $2 == "c" ]
            then
                echo -e "        ${G}${B}create${N} $dir/main.c"
            elif [ $2 == "cpp" ]
            then
                echo -e "        ${G}${B}create${N} $dir/main.cpp"
            fi
        fi
    done

    cp -- "$ycm_conf" "$tar/.ycm_extra_conf.py"
    echo -e "        ${G}${B}create${N} .ycm_extra_conf.py"

    cp -- "$make_file" "$tar/Makefile"
    echo -e "        ${G}${B}create${N} Makefile"

    eval "cd $tar && ctags -R"
    echo -e "        ${G}${B}create${N} tags"

    touch "$tar/cscope.files"
    echo -e "        ${G}${B}create${N} cscope.files"

    touch "$tar/cscope.out"
    echo -e "        ${G}${B}create${N} cscope.out"

    echo ""

    exit
else
    echo "Error(too many args) : type 2 args; project name / language type"

    exit
fi

