#!/bin/bash

if [ $# -eq 0 ] 
then
    echo "Error(no args) : type 2 args; project name / language type"

    exit
elif [ $# -eq 1 ] 
then
    echo "Error(1 arg) : type 2 args; project name / language type"

    exit
elif [ $# -eq 2 ]
then
    if [ $2 == "c" ]
    then
        ycm_conf="$HOME/.vim/ycm_extra_conf_set/ycm_extra_conf.c.py"
        init_src="$HOME/.xnixc/resource/main.c"
    elif [ $2 == "cpp" ]
    then
        ycm_conf="$HOME/.vim/ycm_extra_conf_set/ycm_extra_conf.cpp.py"
        init_src="$HOME/.xnixc/resource/main.cpp"
    else
        echo "Error(invalid arg) : invalid language type; valid - c / cpp"

        exit
    fi

    tar="$PWD/$1"

    if [ -d $tar ] 
    then
        echo "Error : directory already exist; duplicate name"

        exit
    fi

    mkdir "$tar"
    echo ""
    echo -e "    \e[32m\e[1mcreate\e[0m new \e[31m\e[1m$2\e[0m project" \
            "\e[36m\e[1m$1\e[0m"

    sub_dirs=( "bin" "build" "doc" "include" "lib" "resource" "spike" "src" 
               "test" )
    
    for dir in "${sub_dirs[@]}"
    do
        mkdir "$tar/$dir"
        touch "$tar/$dir/.keep"
        echo -e "        \e[32m\e[1mcreate\e[0m $dir/"
        if [ $dir == "src" ]
        then
            cp -- "$init_src" "$tar/$dir/"

            if [ $2 == "c" ]
            then
                echo -e "        \e[32m\e[1mcreate\e[0m $dir/main.c"
            elif [ $2 == "cpp" ]
            then
                echo -e "        \e[32m\e[1mcreate\e[0m $dir/main.cpp"
            fi
        fi
    done

    cp -- "$ycm_conf" "$tar/.ycm_extra_conf.py"
    echo -e "        \e[32m\e[1mcreate\e[0m .ycm_extra_conf.py"

    eval "cd $tar && ctags -R"
    echo -e "        \e[32m\e[1mcreate\e[0m tags"

    touch "$tar/cscope.files"
    echo -e "        \e[32m\e[1mcreate\e[0m cscope.files"

    touch "$tar/cscope.out"
    echo -e "        \e[32m\e[1mcreate\e[0m cscope.out"

    echo ""

    exit
else
    echo "Error(too many args) : type 2 args; project name / language type"

    exit
fi

